[phases.setup]
nixPkgs = ["nodejs", "google-chrome", "cacert"]

[phases.install]
cmds = ["npm install"]

[phases.build]
# This line is mandatory for Puppeteer 21+. It forces the browser into a known Linux folder.
cmds = ["PUPPETEER_CACHE_DIR=/root/.cache/puppeteer npx puppeteer browsers install chrome"]

[start]
cmd = "node index.js"